### ISSUE TITLE
Target multiple root elements

### ISSUE THREAD

**Issue by 5tormTrooper** [jackall3n/postcss-scope#5]
I need to apply the tailwind classes to multiple root elements, as I'm using HeadlessUI, which adds Dialogue and Portal components to the root level (e.g. `#headlessui-portal-root` is appended to the `body`), which use TailwindCSS classes.

Since there is no current solution for change the root element for those components (see: https://github.com/tailwindlabs/headlessui/discussions/666), it seems like the simplest solution is to target multiple root elements here.

If I add this
```
"postcss-scope": "#__next, #second-el",
```
to postcss.config.js, 
The selectors are generated like this:
![CleanShot 2023-08-07 at 11 26 39](https://github.com/jackall3n/postcss-scope/assets/4154407/af51b8b1-40b5-451f-8728-2db60527c5e8)

Could `postcss-scope` consider comma-separated selectors in the config?

**Comment by jackall3n** [comment]
Hey @5tormTrooper,

Thanks for the request and nice idea. I've added this functionality in #6. Let me know if that works for you.

**Comment by jackall3n** [comment]
Released in [1.7.0](https://www.npmjs.com/package/postcss-scope/v/1.7.0)

**Comment by 5tormTrooper** [comment]
Works like a charm. Thanks!
